CREATE TABLE `analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessUrl` varchar(500),
	`businessLocation` varchar(500) NOT NULL,
	`industry` varchar(255),
	`status` enum('pending','collecting','analyzing','completed','failed') NOT NULL DEFAULT 'pending',
	`seoScore` int,
	`metaTitle` text,
	`metaDescription` text,
	`headingStructure` json,
	`contentWordCount` int,
	`hasGoogleBusiness` int,
	`googleRating` decimal(2,1),
	`googleReviewCount` int,
	`socialProfiles` json,
	`overallAnalysis` text,
	`strengths` json,
	`weaknesses` json,
	`opportunities` json,
	`recommendations` json,
	`generatedBlogPost` text,
	`generatedAdCopy` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysisId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`url` varchar(500),
	`address` varchar(500),
	`phone` varchar(50),
	`placeId` varchar(255),
	`googleRating` decimal(2,1),
	`googleReviewCount` int,
	`businessTypes` json,
	`seoScore` int,
	`metaTitle` text,
	`metaDescription` text,
	`headingStructure` json,
	`contentWordCount` int,
	`topKeywords` json,
	`socialProfiles` json,
	`employeeCount` varchar(50),
	`fundingInfo` text,
	`techStack` json,
	`recentNews` json,
	`competitiveScore` int,
	`threatLevel` enum('low','medium','high'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `competitors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `industryBenchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`industry` varchar(255) NOT NULL,
	`avgSeoScore` int,
	`avgGoogleRating` decimal(2,1),
	`avgReviewCount` int,
	`avgContentWordCount` int,
	`topKeywords` json,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `industryBenchmarks_id` PRIMARY KEY(`id`),
	CONSTRAINT `industryBenchmarks_industry_unique` UNIQUE(`industry`)
);
